### ISSUE TITLE
Unfriendly Kotlin Java syntax is confused

### ISSUE THREAD

**Issue by FangTaoTao** [anruence/enode#130]
Kotlin Java syntax is confused. Expressing incomprehension。

**Comment by anruence** [comment]
> Kotlin Java syntax is confused. Expressing incomprehension。

for example ?

**Comment by FangTaoTao** [comment]
> > Kotlin Java 语法很混乱。表示不解。
> 
> 例如 ？

As a native Java developer, I am not familiar with Kotlin syntax. Many native classes use Kotlin grammar, which is very inconvenient to understand the code ideas.

**Comment by anruence** [comment]
> > > Kotlin Java 语法很混乱。表示不解。
> > 
> > 
> > 例如 ？
> 
> As a native Java developer, I am not familiar with Kotlin syntax. Many native classes use Kotlin grammar, which is very inconvenient to understand the code ideas.

with the benifit of coroutine, I think kotlin is the most suitable solution, I have to use the hybrid develop mode in the code. For Java developers, I am not used to the syntax of kotlin at first, but in fact, kotlin is more concise and efficient, Later, I plan to use kotlin as the main language of this project. Thank you for your attention and advice.
