### ISSUE TITLE
关于生产的使用问题

### ISSUE THREAD

**Issue by xiawanyingtest** [anruence/enode#145]
1.请问这个我可以使用在生产环境吗？
（1）.项目预计并发量大概每秒几百，压力也不算大，说小也不算小
（2）.项目期望稳定性高，不要有明显的故障
（3）.数据没有混乱异常问题
2.如何使用生产，我改如何选择分支情况？

**Comment by anruence** [comment]
@xiawanyingtest  你好，欢迎关注，简单针对你的问题做下回答哈
1. 这个是否可以应用在生产环境？
1.1 项目预计并发量大概每秒几百。你说的应该是QPS吧，enode是基于分布式消息队列来扩容的，这块没有太大的问题
1.2 稳定性高，不要有明显的故障。这块也是没有什么问题的，我这边其实把大部分的test case覆盖了，但个人能力、时间、精力还是有限，不能完全保证不出故障。在使用开源解决方案时，我觉得首先要很熟悉这个项目的设计，适用场景，但生产场景中难免会遇到一些意想不到的场景，出了问题，这个只能case by case的去解决了，同时建议把问题也放在issue中，也是对社区的一种反哺，也欢迎感兴趣的同学提出新想法，一起把项目做的更好
1.3 数据没有混乱异常问题。这个一般开源方案针对核心的逻辑都会测试完备的，我简单说下这边对你说的混乱异常的理解哈，你说的混乱应该是指enode依赖了两张表，你要很明确的知道两张表的数据代表什么含义，在你引入这种外部依赖时其实就做了trade off，针对不同的数据的保障级别也不一样，遇到问题时也有可能需要你自己定制一些修补工具

2. 如何选择分支情况？
目前我已经把jar发布到maven核心仓库，也是经过完备的测试才发布上去的，可直接选择maven中的版本，代码是为了跟踪提交记录

综上：在选择开源方案时，其实你面临的问题，不止你上面说的那么少，对于新技术的尝试大部分都是解决了一些问题但同时带来了另外的问题，enode还比较年轻，目前只是提供DDD解决思路，周边的解决方案我已经尽最大可能的集成了，尽可能保持通用，但难免会有一些定制的逻辑，这些就需要和内部的基建生态来融合了
