### ISSUE TITLE
聚合根实现使用切面实现，不要使用继承实现；

### ISSUE THREAD

**Issue by lifelong0811** [anruence/enode#29]
原因：
1，Java不支持多继承，实际使用的时候如果继承了AggregateRoot，会导致用户使用过程中受限；
2、继承关于不利于解耦用户代码和enode核心代码；

**Comment by anruence** [comment]
仔细想了下，通过继承AggregateRoot能够直接明确表示是聚合根，同时规范了聚合根的使用方式，如果使用注解之类的方式，很容易忘记定义聚合根相关的id version等信息
