### ISSUE TITLE
基准测试

### ISSUE THREAD

**Issue by xiawanyingtest** [anruence/enode#41]
建议：
提供基准测试数据

**Comment by xiawanyingtest** [comment]
建议：提供英语版md

**Comment by anruence** [comment]
> 建议：
> 提供基准测试数据

在NoteController中提供了性能测试的方法
使用CommandReturnType.EventHandled这个模式处理100000条消息
采用InMemoryEventStore时，100000 个消息约19040ms，QPS:5000左右
采用MysqlMemoryEventStore时，QPS只有400左右
初步猜想性能瓶颈在于实现C# await语法糖时使用了future的join()操作，线程切换频繁
