### ISSUE TITLE
当消息未有返回值的情况，空指针异常，且控制台日志未输出。

### ISSUE THREAD

**Issue by 654894017** [anruence/enode#79]
DefaultCommandListener 类  56行空指针异常， ReplyAddress有可能为空

commandItems.put(SysProperties.ITEMS_COMMAND_REPLY_ADDRESS_KEY,InetUtil.toStringAddress(commandMessage.getReplyAddress()));

**Comment by anruence** [comment]
感谢提醒，会在1.0.8版本进行修复

**Comment by 654894017** [comment]
赞
