### ISSUE TITLE
没有join 或者get  会存在没有发送成功的情况

### ISSUE THREAD

**Issue by 654894017** [anruence/enode#84]
https://github.com/anruence/enode/blob/cd4b0c994ac56eeee0c91436c3c75bdc390b626f/samples/bank-transfer/event-consumer/src/main/java/org/enodeframework/samples/eventhandlers/bank/processmanagers/TransferTransactionProcessManager.java#L56

**Comment by anruence** [comment]
之前转账的ProcessManager功能只实现了一半，我尽快把功能完整实现
