### ISSUE TITLE
Process Manager（Saga）

### ISSUE THREAD

**Issue by xiawanyingtest** [anruence/enode#9]
这个注解怎么写的？有文档吗

**Comment by anruence** [comment]
> 这个注解怎么写的？有文档吗

没有Saga注解，你是看到Axon的Saga实现才有这个疑问的吗
Saga 就是基于 Event 来实现的

**Comment by xiawanyingtest** [comment]
是看了axon的设计，你的例子里怎么c#的代码，能改成java，或者kotlin吗？

**Comment by anruence** [comment]
Conference的例子正在改造中，你可以先看下bank-transfer的例子啊
