### ISSUE TITLE
测试TPS上不去

### ISSUE THREAD

**Issue by 654894017** [anruence/enode#92]
**压测接口：**
http://localhost:8080/bank/deposit?data=1

**前提：**
所有服务都运行在本机
tomcat线程数已经调整到200
用的rocketmq 本地环境
mysql模式 本地mysql版本5.6 

**实际jmeter情况：**
bank/deposit 该接口的TPS为8

**排查情况:**
手动压测单表 event_stream  insert  tps 在7800左右（排除本地mysql问题，用的Jdbctemplate）
memory rocketmq 模式下 接口bank/deposit   TPS为100  （这个猜测是正常的，因为rocketmq是本地代码debug启动，未做优化）

**Comment by anruence** [comment]
> **压测接口：**
> http://localhost:8080/bank/deposit?data=1
> 
> **前提：**
> 所有服务都运行在本机
> tomcat线程数已经调整到200
> 用的rocketmq 本地环境
> mysql模式 本地mysql版本5.6
> 
> **实际jmeter情况：**
> bank/deposit 该接口的TPS为8
> 
> **排查情况:**
> 手动压测单表 event_stream insert tps 在7800左右（排除本地mysql问题，用的Jdbctemplate）
> memory rocketmq 模式下 接口bank/deposit TPS为100 （这个猜测是正常的，因为rocketmq是本地代码debug启动，未做优化）

建议使用JProfile分析出性能热点，盲猜几个地方是有可能导致性能问题的
1. 使用vert.x实现的socket server性能不佳
2. vert.x 异步JDBC驱动默认配置是有优化空间的
3. Jackson序列化性能

**Comment by 654894017** [comment]
> > **压测接口：**
> > http://localhost:8080/bank/deposit?data=1
> > **前提：**
> > 所有服务都运行在本机
> > tomcat线程数已经调整到200
> > 用的rocketmq 本地环境
> > mysql模式 本地mysql版本5.6
> > **实际jmeter情况：**
> > bank/deposit 该接口的TPS为8
> > **排查情况:**
> > 手动压测单表 event_stream insert tps 在7800左右（排除本地mysql问题，用的Jdbctemplate）
> > memory rocketmq 模式下 接口bank/deposit TPS为100 （这个猜测是正常的，因为rocketmq是本地代码debug启动，未做优化）
> 
> 建议使用jprofiler分析出性能热点，盲猜几个地方是有可能导致性能问题的
> 
> 1. 使用vert.x实现的socket server性能不佳
> 2. vert.x 异步JDBC驱动默认配置是有优化空间的
> 3. Jackson序列化性能

有空按照思路排查一下，感谢   (•́へ•́╬)
