### ISSUE TITLE
订单座位指派聚合根的ID用的是订单聚合根的ID,  这样在后续指派座位或者取消座位的时候，不是会出现聚合根version冲突？ 

### ISSUE THREAD

**Issue by 654894017** [anruence/enode#93]
https://github.com/anruence/enode/blob/e0c46b1fb4d20119455311ff63dc363e1b20ceda/samples/conference/registration-bc/src/main/java/com/microsoft/conference/registration/commandhandler/OrderSeatAssignmentsCommandHandler.java#L21

**Comment by 654894017** [comment]
public AssignSeat(String orderId) {
        super(orderId);
    }

是这个构造参数命名错误了，不应该叫orderId，是预定id

**Comment by 654894017** [comment]
看晕了是这个参数名字写错了

    public AssignSeat(String orderId) {
        super(orderId);
    }
这个构造参数不能叫orderId  是assignmentsId

**Comment by anruence** [comment]
> 看晕了是这个参数名字写错了
> 
> ```
> public AssignSeat(String orderId) {
>     super(orderId);
> }
> ```
> 
> 这个构造参数不能叫orderId 是assignmentsId

小哥真是慧眼啊，这里写错了

**Comment by 654894017** [comment]
哈哈哈哈   在看conference的聚合根这块，   看着订单座位指派聚合根-指派座位命令传orderId作为聚合根id发现的。
