### ISSUE TITLE
测试的时候，有意停掉event_constumer,command_constumer,command_web 再次启动一直重复该提示（同一批数据一直在刷，），访问测试接口巨慢。

### ISSUE THREAD

**Issue by 654894017** [anruence/enode#95]
16:06:03.700 logback [vert.x-eventloop-thread-6] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e680cfab00cd5904bbe08, aggregateRootTypeName: org.enodeframework.samples.domain.bank.transfertransaction.TransferTransaction, version: 2, current nextExpectingEventVersion: 2
16:06:03.700 logback [vert.x-eventloop-thread-8] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e6809fab00cd5904bbcf4, aggregateRootTypeName: org.enodeframework.samples.domain.bank.deposittransaction.DepositTransaction, version: 3, current nextExpectingEventVersion: 3
16:06:03.700 logback [vert.x-eventloop-thread-9] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e6803fab00cd5904bba48, aggregateRootTypeName: org.enodeframework.samples.domain.bank.bankaccount.BankAccount, version: 3, current nextExpectingEventVersion: 3
16:06:03.700 logback [vert.x-eventloop-thread-15] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e6807fab00cd5904bbc39, aggregateRootTypeName: org.enodeframework.samples.domain.bank.deposittransaction.DepositTransaction, version: 3, current nextExpectingEventVersion: 3
16:06:03.701 logback [vert.x-eventloop-thread-10] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e6800fab00cd5904bb8e9, aggregateRootTypeName: org.enodeframework.samples.domain.bank.bankaccount.BankAccount, version: 4, current nextExpectingEventVersion: 4
16:06:03.701 logback [vert.x-eventloop-thread-11] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e680cfab00cd5904bbe00, aggregateRootTypeName: org.enodeframework.samples.domain.bank.deposittransaction.DepositTransaction, version: 2, current nextExpectingEventVersion: 2
16:06:03.701 logback [vert.x-eventloop-thread-12] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e680cfab00cd5904bbe1e, aggregateRootTypeName: org.enodeframework.samples.domain.bank.deposittransaction.DepositTransaction, version: 2, current nextExpectingEventVersion: 2
16:06:03.701 logback [vert.x-eventloop-thread-13] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e6801fab00cd5904bb965, aggregateRootTypeName: org.enodeframework.samples.domain.bank.bankaccount.BankAccount, version: 4, current nextExpectingEventVersion: 4
16:06:03.702 logback [vert.x-eventloop-thread-14] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e680cfab00cd5904bbe26, aggregateRootTypeName: org.enodeframework.samples.domain.bank.bankaccount.BankAccount, version: 2, current nextExpectingEventVersion: 2
16:06:03.702 logback [vert.x-eventloop-thread-1] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e67fffab00cd5904bb8bd, aggregateRootTypeName: org.enodeframework.samples.domain.bank.bankaccount.BankAccount, version: 4, current nextExpectingEventVersion: 4
16:06:03.702 logback [vert.x-eventloop-thread-0] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e680cfab00cd5904bbe22, aggregateRootTypeName: org.enodeframework.samples.domain.bank.transfertransaction.TransferTransaction, version: 2, current nextExpectingEventVersion: 2
16:06:03.702 logback [vert.x-eventloop-thread-3] INFO  o.e.eventing.ProcessingEventMailBox - org.enodeframework.eventing.ProcessingEventMailBox nextExpectingEventVersion ignored, aggregateRootId: 5f9e6809fab00cd5904bbd05, aggregateRootTypeName: org.enodeframework.samples.domain.bank.bankaccount.BankAccount, version: 2, current nextExpectingEventVersion: 2

**Comment by 654894017** [comment]
掉头发，看源码没看到啥原因，水平不够。  |ू･ω･` )

**Comment by 654894017** [comment]
排查聚合根 5f9ecf82fab00cedf831e063 的published_version -》 version = 2  和  event_stream.version 最大版本号-》 version=2
，实际事件已经发送成功，只是mq未标记该消息已消费成功，当重启时，事件重新投入到重试队列，版本号不对导致一直重试。还没找到原因   (￣^￣゜)尴尬

**Comment by anruence** [comment]
> 排查聚合根 5f9ecf82fab00cedf831e063 的published_version -》 version = 2 和 event_stream.version 最大版本号-》 version=2
> ，实际事件已经发送成功，只是mq未标记该消息已消费成功，当重启时，事件重新投入到重试队列，版本号不对导致一直重试。还没找到原因 (￣^￣゜)尴尬

有可能是消息处理地方的BUG，之前出过一次问题，后来我一直复现不了。可QQ联系我：765879200

**Comment by anruence** [comment]
> 排查聚合根 5f9ecf82fab00cedf831e063 的published_version -》 version = 2 和 event_stream.version 最大版本号-》 version=2
> ，实际事件已经发送成功，只是mq未标记该消息已消费成功，当重启时，事件重新投入到重试队列，版本号不对导致一直重试。还没找到原因 (￣^￣゜)尴尬

应该找到问题了，这行判断时用错字段了，这样remove旧的数据应该就好了， version -> key
https://github.com/anruence/enode/blob/master/enode/src/main/java/org/enodeframework/eventing/ProcessingEventMailBox.java#L45 
我这边压测时没有继续复现了，你可以重新测试下~
